### PR TITLE
website-content-extraction

### PR DESCRIPTION
**Pull request by skrichef**
## CHANGE TYPE 

[X  ] New Feature 

[  ] Feature Update 

[  ] Bug Fix 

## GOAL 

 Extracts the body content from a single link that contains a pdf

## DETAILED DESCRIPTION 

From **https://weeklyjoys.wordpress.com/wp-content/uploads/2021/10/ece404_e1_sp2021.pdf**, 
**extract_body_text.py** will create a .txt file called **ece404_e1_sp2021.txt** that contains all the pdf content in text format.
**webcrawl_functions.py** has a list of helper functions to assist extract_body_text.py

## REQUESTING SPECIFIC ATTENTION ON 
Changes made outside of main such as toml file and other build content
 

## REQUESTING REVIEW BY: 

[ X ] Josh 

[  ] Seth 

[ X ] Emma

### CODE REVIEW

**Comment by JPKamphuis** [comment]
'poetry install' worked fine to install the necessary packages, and code ran without issue. Before a merge: the text file that is created is automatically placed in whatever directory your terminal is in. extract_body_text.py should probably place it in the webcrawl folder or in a specific folder within that webcrawl folder. 
Consideration for the future: how are we going to save and display images that are part of the exam question, like the hieroglyphics or letter frequency in the test this code reads?

**Review by JPKamphuis — COMMENTED** [review]
I wrote my comment on the PR instead of in this 'review' section. Writing this to see the difference and have a review submitted.

**Review by emmateff — APPROVED** [review]
Great work Seth! Similar to Josh, I just checked out your branch, ran a poetry update, and was able to run the file and generate the file of extracted content.

I don't think any changes need to be made right now in terms of where that file is being saved. That is something we will figure out down the road once we have more developed and know how we will need to access that extracted information in other parts of the project.

In reviewing the code in extract_body_text.py, I am wondering why we write the hex to a pdf just to then read that pdf again and then remove it. I'm sure you have a reason, it just doesn't make sense from an outside perspective.

Approving! Thanks Seth!

**Comment by emmateff** [comment]
Future consideration regarding writing/saving a new pdf then deleting it:
Where will the storage for creating a new file be coming from
Is this very inefficient

**Review by JPKamphuis — APPROVED** [review]

**Pull request merged**
